FIXUP: qpnp-smb2: Remove duplicate case value POWER_SUPPLY_PROP_INPUT_SUSPEND
This amends commit 2506f86.

../drivers/power/supply/qcom/qpnp-smb2.c:863:7: error: duplicate case value
      'POWER_SUPPLY_PROP_INPUT_SUSPEND'
        case POWER_SUPPLY_PROP_INPUT_SUSPEND:
             ^
../drivers/power/supply/qcom/qpnp-smb2.c:856:7: note: previous case defined here
        case POWER_SUPPLY_PROP_INPUT_SUSPEND:
             ^

Signed-off-by: Adam W. Willis <return.of.octobot@gmail.com>